=== escorponox/xmlTasks/src/main/webapp/xml/agenda.dtd
<!ELEMENT agenda (contactos|citas)*>
        <!ELEMENT contactos (contacto)*>
        <!ELEMENT contacto (nombre|telefono|email|apellidos)*>
        <!ATTLIST contacto
                alias CDATA #REQUIRED>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT telefono (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT apellidos (#PCDATA)>
        <!ELEMENT citas (cita)*>
        <!ELEMENT cita (titulo|lugar|fecha|hora)*>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT lugar (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>
        <!ELEMENT hora (#PCDATA)>

=== escorponox/xmlTasks/src/main/resources/xml/agenda.xml
<?xml version="1.0"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contactos>
        <contacto alias="pavo1">
            <nombre>pavo1nombre</nombre>
            <telefono>999-999-999</telefono>
            <email>aaa@gmail.com</email>
        </contacto>
        <contacto alias="pavo2">
            <nombre>pavo2nombre</nombre>
            <apellidos>pavo2apellidos</apellidos>
            <telefono>999-999-999</telefono>
        </contacto>
    </contactos>
    <citas>
        <cita>
            <titulo>titulo1</titulo>
            <lugar>girona</lugar>
            <fecha>19/11/2015</fecha>
            <hora>19:15</hora>
        </cita>
        <cita>
            <titulo>titulo2</titulo>
            <lugar>girona2</lugar>
            <fecha>19/10/2015</fecha>
            <hora>19:10</hora>
        </cita>
    </citas>
</agenda>

=== escorponox/xmlTasks/src/main/webapp/xml/agenda.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="agenda.xsl"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://myNameSpace.com"
        xsi:schemaLocation="http://myNameSpace.com agenda.xsd">
    <contactos>
        <contacto alias="pavo1">
            <nombre>pavo1nombre</nombre>
            <telefono>999-999-999</telefono>
            <email>aaa@gmail.com</email>
        </contacto>
        <contacto alias="pavo2">
            <nombre>pavo2nombre</nombre>
            <apellidos>pavo2apellidos</apellidos>
            <telefono>999-999-999</telefono>
        </contacto>
        <contacto alias="amigo1">
            <nombre>amigo1</nombre>
            <apellidos>amigo1apellidos</apellidos>
            <telefono>999-999-999</telefono>
        </contacto>
        <contacto alias="amigo2">
            <nombre>amigo2</nombre>
            <apellidos>amigo2apellidos</apellidos>
            <telefono>999-999-999</telefono>
        </contacto>
    </contactos>
    <citas>
        <cita>
            <titulo>titulo1</titulo>
            <lugar>girona</lugar>
            <fecha>2015-02-19</fecha>
            <hora>19:15:00</hora>
        </cita>
        <cita>
            <titulo>titulo2</titulo>
            <lugar>girona2</lugar>
            <fecha>2015-02-21</fecha>
            <hora>19:10:00</hora>
        </cita>
    </citas>
</agenda>
